package manager;

import domain.*;
import util.LottoFactory;
import util.ManualNumberGenerator;
import util.NumbersGenerator;
import util.RandomNumbersGenerator;
import view.InputView;
import view.OutputView;

import java.util.ArrayList;
import java.util.List;

public class LottoManager {

    private LottoFactory lottoFactory;
    private NumbersGenerator randomNumbersGenerator = new RandomNumbersGenerator();

    public LottoManager(LottoFactory lottoFactory) {
        this.lottoFactory = lottoFactory;
    }

    public UserLottos IssuingLottoTickets() {
        Amount amount = getTicketCountFromInput();
        TicketCount ticketCount = TicketCount.from(amount);
        // manual issuing
        ManualLottoCount manualLottoCount = InputView.induceManulLottoCountToBeEntered(ticketCount);
        List<Lotto> manualLottos = generateManualLottos(manualLottoCount);
        // auto issuing
        List<Lotto> autoLottos = generateAutoLottos(ticketCount);

        UserLottos userLottos = UserLottos.of(manualLottos,autoLottos,amount);
        printUserLottos(manualLottoCount,ticketCount,userLottos);
        return userLottos;
    }

    public void calculateAndShowWinningStatistics(UserLottos userLottos){
        WinningNumbers winningNumbers = InputView.induceTheWinningNumberToBeEntered();
        WinningResult winningResult = userLottos.getWinningResult(winningNumbers);
        OutputView.printWinningResultAndStatistics(winningResult,userLottos.getPurchaseAmount());
    }

    private Amount getTicketCountFromInput() {
        return InputView.induceTheAmountToBeEntered();
    }

    private List<Lotto> generateManualLottos(ManualLottoCount manualLottoCount){
        List<List<Integer>> manualLottosNumbers = InputView.readManualNumbers(manualLottoCount);

        List<Lotto> manuallyGenerateLottos = new ArrayList<>();
        for(List<Integer> lottoNumbers : manualLottosNumbers){
            lottoFactory.changeNumberGenerateStrategy(new ManualNumberGenerator(lottoNumbers));
            manuallyGenerateLottos.add(lottoFactory.generateLotto());
        }
        return manuallyGenerateLottos;
    }

    private List<Lotto> generateAutoLottos(TicketCount ticketCount){
        lottoFactory.changeNumberGenerateStrategy(randomNumbersGenerator);
        List<Lotto> autoGeneratedLottos = new ArrayList<>();
        for(int i=0; i< ticketCount.getValue(); i++){
            autoGeneratedLottos.add(lottoFactory.generateLotto());
        }
        return autoGeneratedLottos;
    }

    private void printUserLottos(ManualLottoCount manualLottoCount, TicketCount ticketCount, UserLottos userLottos){
        OutputView.printNumberOfLottoes(manualLottoCount,ticketCount);
        OutputView.printIssuedLottoTickets(userLottos);
    }
}
